server:
  port: 3206
  shutdown: "graceful"

# If you use a database then uncomment the `group:, readiness: and include: "db"` lines in the health probes and uncomment the datasource section
management:
  endpoint:
    health:
      show-details: "always"
      # group:
      #  readiness:
      #   include: "db"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
  health:
    elasticsearch:
      enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan:
    - uk.gov.hmcts.reform.pcs
  writer-with-order-by-keys: true

security:
  anonymousPaths:
    - "/health"
    - "/health/liveness"
    - "/health/readiness"
    - "/swagger-ui.html"
    - "/swagger-ui/**"
    - "/v3/api-docs/**"

spring:
  config:
    import: "optional:configtree:/mnt/secrets/pcs/"
  application:
    name: pcs api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PCS_DB_HOST:localhost}:${PCS_DB_PORT:6432}/${PCS_DB_NAME:pcs}${PCS_DB_OPTIONS:}
    username: ${PCS_DB_USER_NAME:postgres}
    password: ${PCS_DB_PASSWORD:}
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      poolName: PCSHikariCP
      maxLifetime: 7200000
      connectionTimeout: 30000
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show-sql: ${SPRING_JPA_SHOW_SQL:false}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  jms:
    servicebus:
      enabled: ${HEARINGS_SERVICEBUS_ENABLED:false}
      connection-string: ${HEARINGS_SERVICEBUS_CONNECTION_STRING:}
      topic-client-id: ${HEARINGS_SERVICEBUS_TOPIC_CLIENT_ID:${spring.application.name}}
      pricing-tier: ${HEARINGS_SERVICEBUS_PRICING_TIER:standard}
      receive-timeout: ${HEARINGS_SERVICEBUS_RECEIVE_TIMEOUT:60000}
      idle-timeout: ${HEARINGS_SERVICEBUS_IDLE_TIMEOUT:600000}
      hearings-topic: ${HEARINGS_SERVICEBUS_TOPIC:hmc-to-cft-aat}
      hearings-subscription: ${HEARINGS_SERVICEBUS_SUBSCRIPTION:hmc-to-pcs-subscription-aat}
flyway:
  noop:
    strategy: ${FLYWAY_NOOP_STRATEGY:false}
idam:
  api:
    url: ${IDAM_API_URL:http://localhost:5062}
  s2s-auth:
    url: ${IDAM_S2S_AUTH_URL:http://localhost:4502}
    totp_secret: ${PCS_API_S2S_SECRET:AAAAAAAAAAAAAAAA}
    microservice: ${S2S_SERVICE_NAME:pcs_api}
  s2s-authorised:
    services: ${S2S_NAMES_WHITELIST:pcs_api,pcs_frontend,ccd_data}
  system-user:
    username: ${PCS_IDAM_SYSTEM_USERNAME:pcs-system-user@localhost}
    password: ${PCS_IDAM_SYSTEM_PASSWORD:password}
  prd-admin:
    username: ${PCS_PRD_ADMIN_USERNAME:}
    password: ${PCS_PRD_ADMIN_PASSWORD:}
    scope: ${IDAM_PRD_ADMIN_SCOPE:openid profile roles}
  client:
    id: ${IDAM_CLIENT_ID:pcs-api}
    secret: ${IDAM_CLIENT_SECRET:123456}
    redirect_uri: ${IDAM_API_REDIRECT_URL:http://localhost:3001/oauth2/callback}

azure:
  application-insights:
    instrumentation-key: ${pcs.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

hmc:
  deployment-id: ${HMC_DEPLOYMENT_ID:}
  api-url: ${HMC_API_URL:http://localhost:8084}
  serviceId: ${HMC_SERVICE_ID:AAA3}

location-reference:
  api-url: ${LOCATION_REF_URL:http://localhost:8089}
  court-county-type-id: ${COURT_COUNTY_TYPE_ID:10}

notify:
  api-key: ${PCS_NOTIFY_API_KEY:AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA}
  send-email:
    max-retries: ${NOTIFY_SEND_EMAIL_MAX_RETRIES:5}
    backoff-delay-seconds: ${NOTIFY_SEND_EMAIL_BACKOFF_DELAY_SECONDS:300s}
  check-status:
    max-retries: ${NOTIFY_CHECK_STATUS_MAX_RETRIES:5}
    task-delay-seconds: ${NOTIFY_CHECK_STATUS_DELAY_SECONDS:60s}
    backoff-delay-seconds: ${NOTIFY_CHECK_STATUS_BACKOFF_DELAY_SECONDS:3600s}

testing-support:
  enabled: ${ENABLE_TESTING_SUPPORT:true}

# Below sets if DB scheduler can execute on the current instance of the API.
db-scheduler:
  enabled: false # This disables the autoconfiguration of DB Scheduler. Always off.
  executor-enabled: ${DB_SCHEDULER_EXECUTOR_ENABLED:true}
  polling-interval-seconds: 10
  threads: 10

doc_assembly:
  url: ${DOC_ASSEMBLY_URL:http://localhost:8080}
  s2s-authorised:
    services: pcs_api,ccd_data,ccd_gw,ccd_case_document_am_api,ccd_definition,ccd_admin,ccd_ps,ccd

rd-professional:
  api-url: ${RD_PROFESSIONAL_API_URL:http://rd-professional-api-aat.service.core-compute-aat.internal}

fees:
  api:
    url: ${FEES_REGISTER_API_URL:http://localhost:8991}
    service: possession claim
    jurisdiction1: civil
    jurisdiction2: county court
  lookup:
    caseIssueFee:
      channel: default
      event: issue
      applicantType: all
      amountOrVolume: 1
      keyword: PossessionCC
  request:
    max-retries: ${NOTIFY_CHECK_STATUS_MAX_RETRIES:5}
    backoff-delay-seconds: ${NOTIFY_CHECK_STATUS_BACKOFF_DELAY_SECONDS:3600s}

payments:
  api:
    url: ${PAYMENT_API_URL:http://localhost:8083}
    callback-url: ${PAY_CALLBACK_URL:http://host.docker.internal:8096/service-request-update}
  params:
    organisationUrn: Mortgage and Landlord Possession Claims
    hmctsOrgId: AAA3
